### ISSUE TITLE
Scaffolding creates bad test files, "describe is not defined"

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/tutorial#27]
ENVIRONMENT

    $ yarn rw --version
    0.0.1-alpha.31

PROBLEM

Following steps in the tutorial re: scaffolding, run this:

    $ yarn rw g scaffold post

Then restart the process using `yarn rw dev`. Results in this warning:

    yarn run v1.21.1
    $ /Users/chris/proj/aw-redwood/aw/node_modules/.bin/rw dev
      ✔ Generating the Prisma client...
    $ /Users/chris/proj/aw-redwood/aw/node_modules/.bin/dev-server
    $ /Users/chris/proj/aw-redwood/aw/node_modules/.bin/prisma2 generate --watch
    $ /Users/chris/proj/aw-redwood/aw/node_modules/.bin/webpack-dev-server --config ../node_modules/@redwoodjs/core/    config/webpack.development.js
    17:38:36 api | /Users/chris/proj/aw-redwood/aw/api/src/services/posts/posts.test.js:5
    17:38:36 api | describe('posts', () => {
    17:38:36 api | ^
    17:38:36 api |
    17:38:36 api | ReferenceError: describe is not defined
    17:38:36 api |     at Object.<anonymous> (/Users/chris/proj/aw-redwood/aw/api/src/services/posts/posts.test.js:3:1)
    17:38:36 api |     at Module._compile (internal/modules/cjs/loader.js:955:30)
    17:38:36 api |     at Module._compile (/Users/chris/proj/aw-redwood/aw/node_modules/pirates/lib/index.js:99:24)
    17:38:36 api |     at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    17:38:36 api |     at Object.newLoader [as .js] (/Users/chris/proj/aw-redwood/aw/node_modules/pirates/lib/    index.js:104:7)
    17:38:36 api |     at Module.load (internal/modules/cjs/loader.js:811:32)
    17:38:36 api |     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    17:38:36 api |     at Module.require (internal/modules/cjs/loader.js:848:19)
    17:38:36 api |     at require (internal/modules/cjs/helpers.js:74:18)
    17:38:36 api |     at Object.<anonymous> (/Users/chris/proj/aw-redwood/aw/api/src/functions/graphql.js:15:57)
    error Command failed with exit code 1.

Note: `ReferenceError: describe is not defined`

SOLUTION

Appears to be missing `import { describe } from 'something'`

I've tried `jest` and `jasmine` -- will try some others.

**Comment by chris-hailstorm** [comment]
May just be a side-effect of `ncu -u`. Not sure how changes to `package.json` (established via `yarn create redwood-app BLAH`) are handled by `ncu`.  The version of `@redwoodjs/core` in `./package.json` was newer than in `./web/package.json` or `./api/package.json`. 

Maybe should not use `ncu` when there are `yarn` workspaces?

Maybe there is a workspace-aware equivalent of `ncu`?

When I manually bumped the versions and re-ran `yarn`, all is well.

Not sure how many people would try to upgrade in this way.

**Comment by thedavidprice** [comment]
We'll take a look at this. Thanks for taking things for a spin and letting us know.

FYI, we're currently in process with the test file generators. And you likely also caught us in between package releases and updating the bootstrap template -- `alpha.31` just shipped a few hours ago.
