### ISSUE TITLE
“Your browser should open to http://localhost:8910” Browser doesn't auto open

### ISSUE THREAD

**Issue by sw-yx** [redwoodjs/tutorial#4]
*Splitting out notes from https://github.com/redwoodjs/tutorial/pull/3*

In the tutorial, when it says to run redwood dev, it says “Your browser should open to http://localhost:8910” - however the browser didnt auto open for me. Bug or recent change?

**Comment by cannikin** [comment]
Keep in mind the note at the top of the tutorial: we wrote that first and are then working on getting the code to the point that the tutorial actually works. This doesn't work yet, but should soon! :)

**Comment by sw-yx** [comment]
yup, i understand. just reporting stuff as i see it
