### ISSUE TITLE
when i click on localhost:8910, it says 404 Page not found instead of the welcome screen

### ISSUE THREAD

**Issue by sw-yx** [redwoodjs/tutorial#5]
*Splitting out notes from https://github.com/redwoodjs/tutorial/pull/3*

when i click on localhost:8910, it says 404 Page not found instead of the welcome screen. it looks like there is no welcome screen - should we change the tutorial, or change the template?

**Comment by cannikin** [comment]
See note on https://github.com/redwoodjs/tutorial/issues/4

**Comment by peterp** [comment]
This is now working correctly.
