### ISSUE TITLE
FatalErrorPage.js is not present

### ISSUE THREAD

**Issue by sw-yx** [redwoodjs/tutorial#6]
*Splitting out notes from https://github.com/redwoodjs/tutorial/pull/3*

FatalErrorPage.js is not present, but we refer to it in the tutorial. bug in the tutorial, or in the template?

**Comment by cannikin** [comment]
https://github.com/redwoodjs/tutorial/issues/4

**Comment by peterp** [comment]
`FatalErrorPage.js` is now present.
