### ISSUE TITLE
`redwood generate scaffold post` does not work

### ISSUE THREAD

**Issue by sw-yx** [redwoodjs/tutorial#7]
*Splitting out notes from https://github.com/redwoodjs/tutorial/pull/3*

⚠️ `redwood generate scaffold post` simply does not work, this is a blocker for continuing the rest of the tutorial. what is the current workaround, and/or where can i start contributing this functionality (what is it actually meant to do? i'm honestly not suuuper clear)

**Comment by cannikin** [comment]
See note on https://github.com/redwoodjs/tutorial/issues/4

**Comment by cannikin** [comment]
This works now! Although once generated you can't use the page yet. We need to do some auto-mapping of created SDL files to Apollo.

**Comment by peterp** [comment]
The auto-mapping is now complete.
